apiVersion: testsys.system/v1
kind: Test
metadata:
  name: ${CLUSTER_NAME}-test-1-initial
  namespace: testsys
spec:
  agent:
    name: ecs-test-agent
    image: ${ECS_TEST_AGENT_IMAGE_URI}
    keepRunning: true
    configuration:
      clusterName: \${${CLUSTER_NAME}.clusterName}
      region: \${${CLUSTER_NAME}.region}
      assumeRole: ${ASSUME_ROLE}
  dependsOn: []
  resources: [${CLUSTER_NAME}-instances, ${CLUSTER_NAME}]
---  
apiVersion: testsys.system/v1
kind: Test
metadata:
  name: ${CLUSTER_NAME}-test-2-migrate
  namespace: testsys
spec:
  agent:
    configuration:
      awsRegion: ${AWS_REGION}
      instanceIds: \${${CLUSTER_NAME}-instances.ids}
      migrateToVersion: ${UPGRADE_VERSION}
      tufRepo:
        metadataUrl: ${METADATA_URL}
        targetsUrl: ${TARGETS_URL}
      assumeRole: ${ASSUME_ROLE}
    image: ${MIGRATION_TEST_AGENT_IMAGE_URI}
    name: migration-test-agent
    keepRunning: true
  resources: [${CLUSTER_NAME}-instances, ${CLUSTER_NAME}]
  dependsOn: [${CLUSTER_NAME}-test-1-initial]
---
apiVersion: testsys.system/v1
kind: Test
metadata:
  name: ${CLUSTER_NAME}-test-3-migrated
  namespace: testsys
spec:
  agent:
    name: ecs-test-agent
    image: ${ECS_TEST_AGENT_IMAGE_URI}
    keepRunning: true
    configuration:
      clusterName: \${${CLUSTER_NAME}.clusterName}
      region: \${${CLUSTER_NAME}.region}
      assumeRole: ${ASSUME_ROLE}
  dependsOn: [${CLUSTER_NAME}-test-2-migrate]
  resources: [${CLUSTER_NAME}-instances, ${CLUSTER_NAME}]
---
apiVersion: testsys.system/v1
kind: Test
metadata:
  name: ${CLUSTER_NAME}-test-4-migrate
  namespace: testsys
spec:
  agent:
    configuration:
      awsRegion: ${AWS_REGION}
      instanceIds: \${${CLUSTER_NAME}-instances.ids}
      migrateToVersion: ${STARTING_VERSION}
      tufRepo:
        metadataUrl: ${METADATA_URL}
        targetsUrl: ${TARGETS_URL}
      assumeRole: ${ASSUME_ROLE}
    image: ${MIGRATION_TEST_AGENT_IMAGE_URI}
    name: migration-test-agent
    keepRunning: true
  resources: [${CLUSTER_NAME}-instances, ${CLUSTER_NAME}]
  dependsOn: [${CLUSTER_NAME}-test-3-migrated]
---
apiVersion: testsys.system/v1
kind: Test
metadata:
  name: ${CLUSTER_NAME}-test-5-final
  namespace: testsys
spec:
  agent:
    name: ecs-test-agent
    image: ${ECS_TEST_AGENT_IMAGE_URI}
    keepRunning: true
    configuration:
      clusterName: \${${CLUSTER_NAME}.clusterName}
      region: \${${CLUSTER_NAME}.region}
      assumeRole: ${ASSUME_ROLE}
  dependsOn: [${CLUSTER_NAME}-test-4-migrate]
  resources: [${CLUSTER_NAME}-instances, ${CLUSTER_NAME}]
---
apiVersion: testsys.system/v1
kind: Resource
metadata:
  name: ${CLUSTER_NAME}
  namespace: testsys
spec:
  agent:
    name: ecs-provider
    image: ${ECS_RESOURCE_AGENT_IMAGE_URI}
    keepRunning: true
    configuration:
      clusterName: ${CLUSTER_NAME}
      region: ${AWS_REGION}
      assumeRole: ${ASSUME_ROLE}
  dependsOn: []
  destructionPolicy: onDeletion
---
apiVersion: testsys.system/v1
kind: Resource
metadata:
  name: ${CLUSTER_NAME}-instances
  namespace: testsys
spec:
  agent:
    name: ec2-provider
    image: ${EC2_RESOURCE_AGENT_IMAGE_URI}
    keepRunning: true
    configuration:
      clusterName: \${${CLUSTER_NAME}.clusterName}
      clusterType: ecs
      instanceCount: 2
      nodeAmi: ${BOTTLEROCKET_AMI_ID}
      region: ${AWS_REGION}
      instanceProfileArn: \${${CLUSTER_NAME}.iamInstanceProfileArn}
      subnetIds: \${${CLUSTER_NAME}.publicSubnetIds}
      instanceTypes: ["m5.large"]
      assumeRole: ${ASSUME_ROLE}
  dependsOn: [${CLUSTER_NAME}]
  destructionPolicy: onDeletion
