' render with:
' docker run -d -p 8080:8080 plantuml/plantuml-server:jetty
' http://localhost:8080
@startuml
title TestSys Sequence Diagram

participant "TestSys CLI"                  as cli
database    "Kubernetes"                   as k8s
control     "Controller"                   as ctl
participant "Resource Pod A"               as raa
participant "Resource Pod B"               as rab
participant "Test Pod"                     as ta

cli -> k8s: \
Create CRDs for resources A, B and test

''''''''''''''''''''''''''''''''''''''''''''''''''

ctl -> k8s: \
Update test status

''''''''''''''''''''''''''''''''''''''''''''''''''
' Resource Provider A
''''''''''''''''''''''''''''''''''''''''''''''''''

ctl -> k8s: \
Run resource provider A

''''''''''''''''''''''''''''''''''''''''''''''''''

raa -> k8s: \
Update Status

raa -> raa: \
Create A resources

''''''''''''''''''''''''''''''''''''''''''''''''''

raa -> k8s: \
Update status

''''''''''''''''''''''''''''''''''''''''''''''''''
' Resource Provider B
''''''''''''''''''''''''''''''''''''''''''''''''''

ctl -> k8s: \
Run resource provider B

''''''''''''''''''''''''''''''''''''''''''''''''''

rab -> k8s: \
Update status

rab -> rab: \
Create B resources

''''''''''''''''''''''''''''''''''''''''''''''''''

rab -> k8s: \
Update status

''''''''''''''''''''''''''''''''''''''''''''''''''
' Run the Test
''''''''''''''''''''''''''''''''''''''''''''''''''

ctl -> k8s: \
Run test pod

''''''''''''''''''''''''''''''''''''''''''''''''''

ta -> k8s: \
Update status

ta -> ta: \
Run test

''''''''''''''''''''''''''''''''''''''''''''''''''

ta -> k8s: \
Update status

''''''''''''''''''''''''''''''''''''''''''''''''''
' Cleanup
''''''''''''''''''''''''''''''''''''''''''''''''''

cli -> k8s: Get info about tests or resources
cli -> k8s: Delete test and resource CRD instances

''''''''''''''''''''''''''''''''''''''''''''''''''
' Delete Resource B
''''''''''''''''''''''''''''''''''''''''''''''''''

ctl -> k8s: \
Run destruction pod `B`

rab -> k8s: \
Update Status

rab -> rab: Delete `B` resources

rab -> k8s: \
Update Status

''''''''''''''''''''''''''''''''''''''''''''''''''
' Delete Resource A
''''''''''''''''''''''''''''''''''''''''''''''''''

ctl -> k8s: \
Run destruction pod `A`

raa -> k8s: \
Update status

raa -> raa: Destroy `A` resources

raa -> k8s: \
Update status

ctl -> k8s: Delete test pod
ctl -> k8s: Delete CRD instances

@enduml
