name: Tools
on:
  pull_request:
    paths:
      - 'Makefile'
      - 'clarify.toml'
      - 'deny.toml'
      - 'tools/**'
  push:
    paths:
      - 'Makefile'
      - 'clarify.toml'
      - 'deny.toml'
      - 'tools/**'
    branches: [develop]
jobs:
  images:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      # Build local tools container in case we are working on a new tools release
      - run: make tools
      - run: make images
