name: Tools
on:
  pull_request:
    paths:
      - 'Makefile'
      - 'clarify.toml'
      - 'deny.toml'
      - 'tools/**'
  push:
    paths:
      - 'Makefile'
      - 'clarify.toml'
      - 'deny.toml'
      - 'tools/**'
    branches: [develop]
jobs:
  images:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      # Build local tools container in case we are working on a new tools release
      - run: make tools
      - run: make images
